name: Terraform CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_ENVIRONMENT: "dev"  # Change this to the desired environment if needed
      SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: true

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -chdir=dev  # Specify the working directory

      - name: Terraform Validate
        run: terraform validate -chdir=dev  # Specify the working directory

      - name: Terraform Plan
        id: plan
        run: terraform plan \
          -chdir=dev \  # Specify the working directory
          -var="snowflake_username=${SNOWFLAKE_USERNAME}" \
          -var="snowflake_password=${SNOWFLAKE_PASSWORD}" \
          -var="snowflake_account=${SNOWFLAKE_ACCOUNT}" \
          -out=tfplan
        continue-on-error: true

      - name: Terraform Apply (Approve Only)
        if: github.event_name == 'push'
        run: terraform apply -chdir=dev -auto-approve tfplan  # Specify the working directory
